In [33]:
import pandas as pd

# Load the full DMV dataset
df = pd.read_csv("DMV Bank Dataset.csv")

# Keep only Virginia branches
df = df[df['STNAME'] == 'Virginia']

In [34]:
df.columns

Index(['YEAR', 'CERT', 'NAMEFULL', 'ADDRESBR', 'BRNUM', 'UNINUMBR', 'STALPBR',
       'ADDRESS', 'BKCLASS', 'CITY', 'STALP', 'STCNTY', 'STNAME', 'ZIP',
       'CNTYNAMB', 'DEPSUMBR', 'NAMEBR', 'SIMS_ESTABLISHED_DATE',
       'SIMS_LATITUDE', 'SIMS_LONGITUDE'],
      dtype='object')

In [35]:
df.head()

,YEAR,CERT,NAMEFULL,ADDRESBR,BRNUM,UNINUMBR,STALPBR,ADDRESS,BKCLASS,CITY,STALP,STCNTY,STNAME,ZIP,CNTYNAMB,DEPSUMBR,NAMEBR,SIMS_ESTABLISHED_DATE,SIMS_LATITUDE,SIMS_LONGITUDE
7184,2024,823,Citizens Bank and Trust Company,126 S Main St,0,518,VA,126 S Main St,SM,Blackstone,VA,51135,Virginia,23824,Nottoway,151685,Citizens Bank And Trust Company,07/15/1873,37.079760,-77.998135
7185,2024,823,Citizens Bank and Trust Company,101 N Main St,1,186002,VA,126 S Main St,SM,Blackstone,VA,51135,Virginia,23824,Nottoway,0,Drive-In Branch,7/29/1966,37.080598,-77.997579
7186,2024,823,Citizens Bank and Trust Company,622 E Atlantic St,10,465187,VA,126 S Main St,SM,Blackstone,VA,51135,Virginia,23824,Mecklenburg,16346,South Hill Branch,11/30/2006,36.721200,-78.119366
7187,2024,823,Citizens Bank and Trust Company,2501 Anderson Hwy,11,617240,VA,126 S Main St,SM,Blackstone,VA,51135,Virginia,23824,Powhatan,17559,Powhatan Branch,9/23/2019,37.521730,-77.821405
7188,2024,823,Citizens Bank and Trust Company,210 Carter St,2,186003,VA,126 S Main St,SM,Blackstone,VA,51135,Virginia,23824,Nottoway,44082,Crewe Branch,5/31/1972,37.176266,-78.123508

In [36]:
#missing values in any column
df.isnull().sum()

YEAR                     0
CERT                     0
NAMEFULL                 0
ADDRESBR                 0
BRNUM                    0
UNINUMBR                 0
STALPBR                  0
ADDRESS                  0
BKCLASS                  0
CITY                     0
STALP                    0
STCNTY                   0
STNAME                   0
ZIP                      0
CNTYNAMB                 0
DEPSUMBR                 0
NAMEBR                   0
SIMS_ESTABLISHED_DATE    0
SIMS_LATITUDE            0
SIMS_LONGITUDE           0
dtype: int64

In [37]:
df.duplicated().sum()

0

In [38]:
# Keep only useful columns for Virginia bank data
df = df[['CERT', 'NAMEFULL', 'ADDRESBR', 'CITY', 'STNAME', 'ZIP',
         'DEPSUMBR', 'NAMEBR', 'SIMS_ESTABLISHED_DATE', 'SIMS_LATITUDE', 'SIMS_LONGITUDE']]

# Convert date column for Virginia bank data
df['SIMS_ESTABLISHED_DATE'] = pd.to_datetime(df['SIMS_ESTABLISHED_DATE'], errors='coerce')

Virginia Climate Dataset
This dataset shows climate risk scores for each county in VA.
It includes population and ratings that describe how likely each county is to face things like floods, heat, and other disasters.

In [39]:
climate_va = pd.read_csv("Virginia Climate Dataset.csv")
list(climate_va.columns)

['OID_',
 'NRI_ID',
 'STATE',
 'STATEABBRV',
 'STATEFIPS',
 'COUNTY',
 'COUNTYTYPE',
 'COUNTYFIPS',
 'STCOFIPS',
 'POPULATION',
 'BUILDVALUE',
 'AGRIVALUE',
 'AREA',
 'RISK_VALUE',
 'RISK_SCORE',
 'RISK_RATNG',
 'RISK_SPCTL',
 'EAL_SCORE',
 'EAL_RATNG',
 'EAL_SPCTL',
 'EAL_VALT',
 'EAL_VALB',
 'EAL_VALP',
 'EAL_VALPE',
 'EAL_VALA',
 'ALR_VALB',
 'ALR_VALP',
 'ALR_VALA',
 'ALR_NPCTL',
 'ALR_VRA_NPCTL',
 'SOVI_SCORE',
 'SOVI_RATNG',
 'SOVI_SPCTL',
 'RESL_SCORE',
 'RESL_RATNG',
 'RESL_SPCTL',
 'RESL_VALUE',
 'CRF_VALUE',
 'AVLN_EVNTS',
 'AVLN_AFREQ',
 'AVLN_EXP_AREA',
 'AVLN_EXPB',
 'AVLN_EXPP',
 'AVLN_EXPPE',
 'AVLN_EXPT',
 'AVLN_HLRB',
 'AVLN_HLRP',
 'AVLN_HLRR',
 'AVLN_EALB',
 'AVLN_EALP',
 'AVLN_EALPE',
 'AVLN_EALT',
 'AVLN_EALS',
 'AVLN_EALR',
 'AVLN_ALRB',
 'AVLN_ALRP',
 'AVLN_ALR_NPCTL',
 'AVLN_RISKV',
 'AVLN_RISKS',
 'AVLN_RISKR',
 'CFLD_EVNTS',
 'CFLD_AFREQ',
 'CFLD_EXP_AREA',
 'CFLD_EXPB',
 'CFLD_EXPP',
 'CFLD_EXPPE',
 'CFLD_EXPT',
 'CFLD_HLRB',
 'CFLD_HLRP',
 'CFLD_HLRR',
 'CFLD_EALB',
 'CFLD_EALP',
 'CFLD_EALPE',
 'CFLD_EALT',
 'CFLD_EALS',
 'CFLD_EALR',
 'CFLD_ALRB',
 'CFLD_ALRP',
 'CFLD_ALR_NPCTL',
 'CFLD_RISKV',
 'CFLD_RISKS',
 'CFLD_RISKR',
 'CWAV_EVNTS',
 'CWAV_AFREQ',
 'CWAV_EXP_AREA',
 'CWAV_EXPB',
 'CWAV_EXPP',
 'CWAV_EXPPE',
 'CWAV_EXPA',
 'CWAV_EXPT',
 'CWAV_HLRB',
 'CWAV_HLRP',
 'CWAV_HLRA',
 'CWAV_HLRR',
 'CWAV_EALB',
 'CWAV_EALP',
 'CWAV_EALPE',
 'CWAV_EALA',
 'CWAV_EALT',
 'CWAV_EALS',
 'CWAV_EALR',
 'CWAV_ALRB',
 'CWAV_ALRP',
 'CWAV_ALRA',
 'CWAV_ALR_NPCTL',
 'CWAV_RISKV',
 'CWAV_RISKS',
 'CWAV_RISKR',
 'DRGT_EVNTS',
 'DRGT_AFREQ',
 'DRGT_EXP_AREA',
 'DRGT_EXPA',
 'DRGT_EXPT',
 'DRGT_HLRA',
 'DRGT_HLRR',
 'DRGT_EALA',
 'DRGT_EALT',
 'DRGT_EALS',
 'DRGT_EALR',
 'DRGT_ALRA',
 'DRGT_ALR_NPCTL',
 'DRGT_RISKV',
 'DRGT_RISKS',
 'DRGT_RISKR',
 'ERQK_EVNTS',
 'ERQK_AFREQ',
 'ERQK_EXP_AREA',
 'ERQK_EXPB',
 'ERQK_EXPP',
 'ERQK_EXPPE',
 'ERQK_EXPT',
 'ERQK_HLRB',
 'ERQK_HLRP',
 'ERQK_HLRR',
 'ERQK_EALB',
 'ERQK_EALP',
 'ERQK_EALPE',
 'ERQK_EALT',
 'ERQK_EALS',
 'ERQK_EALR',
 'ERQK_ALRB',
 'ERQK_ALRP',
 'ERQK_ALR_NPCTL',
 'ERQK_RISKV',
 'ERQK_RISKS',
 'ERQK_RISKR',
 'HAIL_EVNTS',
 'HAIL_AFREQ',
 'HAIL_EXP_AREA',
 'HAIL_EXPB',
 'HAIL_EXPP',
 'HAIL_EXPPE',
 'HAIL_EXPA',
 'HAIL_EXPT',
 'HAIL_HLRB',
 'HAIL_HLRP',
 'HAIL_HLRA',
 'HAIL_HLRR',
 'HAIL_EALB',
 'HAIL_EALP',
 'HAIL_EALPE',
 'HAIL_EALA',
 'HAIL_EALT',
 'HAIL_EALS',
 'HAIL_EALR',
 'HAIL_ALRB',
 'HAIL_ALRP',
 'HAIL_ALRA',
 'HAIL_ALR_NPCTL',
 'HAIL_RISKV',
 'HAIL_RISKS',
 'HAIL_RISKR',
 'HWAV_EVNTS',
 'HWAV_AFREQ',
 'HWAV_EXP_AREA',
 'HWAV_EXPB',
 'HWAV_EXPP',
 'HWAV_EXPPE',
 'HWAV_EXPA',
 'HWAV_EXPT',
 'HWAV_HLRB',
 'HWAV_HLRP',
 'HWAV_HLRA',
 'HWAV_HLRR',
 'HWAV_EALB',
 'HWAV_EALP',
 'HWAV_EALPE',
 'HWAV_EALA',
 'HWAV_EALT',
 'HWAV_EALS',
 'HWAV_EALR',
 'HWAV_ALRB',
 'HWAV_ALRP',
 'HWAV_ALRA',
 'HWAV_ALR_NPCTL',
 'HWAV_RISKV',
 'HWAV_RISKS',
 'HWAV_RISKR',
 'HRCN_EVNTS',
 'HRCN_AFREQ',
 'HRCN_EXP_AREA',
 'HRCN_EXPB',
 'HRCN_EXPP',
 'HRCN_EXPPE',
 'HRCN_EXPA',
 'HRCN_EXPT',
 'HRCN_HLRB',
 'HRCN_HLRP',
 'HRCN_HLRA',
 'HRCN_HLRR',
 'HRCN_EALB',
 'HRCN_EALP',
 'HRCN_EALPE',
 'HRCN_EALA',
 'HRCN_EALT',
 'HRCN_EALS',
 'HRCN_EALR',
 'HRCN_ALRB',
 'HRCN_ALRP',
 'HRCN_ALRA',
 'HRCN_ALR_NPCTL',
 'HRCN_RISKV',
 'HRCN_RISKS',
 'HRCN_RISKR',
 'ISTM_EVNTS',
 'ISTM_AFREQ',
 'ISTM_EXP_AREA',
 'ISTM_EXPB',
 'ISTM_EXPP',
 'ISTM_EXPPE',
 'ISTM_EXPT',
 'ISTM_HLRB',
 'ISTM_HLRP',
 'ISTM_HLRR',
 'ISTM_EALB',
 'ISTM_EALP',
 'ISTM_EALPE',
 'ISTM_EALT',
 'ISTM_EALS',
 'ISTM_EALR',
 'ISTM_ALRB',
 'ISTM_ALRP',
 'ISTM_ALR_NPCTL',
 'ISTM_RISKV',
 'ISTM_RISKS',
 'ISTM_RISKR',
 'LNDS_EVNTS',
 'LNDS_AFREQ',
 'LNDS_EXP_AREA',
 'LNDS_EXPB',
 'LNDS_EXPP',
 'LNDS_EXPPE',
 'LNDS_EXPT',
 'LNDS_HLRB',
 'LNDS_HLRP',
 'LNDS_HLRR',
 'LNDS_EALB',
 'LNDS_EALP',
 'LNDS_EALPE',
 'LNDS_EALT',
 'LNDS_EALS',
 'LNDS_EALR',
 'LNDS_ALRB',
 'LNDS_ALRP',
 'LNDS_ALR_NPCTL',
 'LNDS_RISKV',
 'LNDS_RISKS',
 'LNDS_RISKR',
 'LTNG_EVNTS',
 'LTNG_AFREQ',
 'LTNG_EXP_AREA',
 'LTNG_EXPB',
 'LTNG_EXPP',
 'LTNG_EXPPE',
 'LTNG_EXPT',
 'LTNG_HLRB',
 'LTNG_HLRP',
 'LTNG_HLRR',
 'LTNG_EALB',
 'LTNG_EALP',
 'LTNG_EALPE',
 'LTNG_EALT',
 'LTNG_EALS',
 'LTNG_EALR',
 'LTNG_ALRB',
 'LTNG_ALRP',
 'LTNG_ALR_NPCTL',
 'LTNG_RISKV',
 'LTNG_RISKS',
 'LTNG_RISKR',
 'RFLD_EVNTS',
 'RFLD_AFREQ',
 'RFLD_EXP_AREA',
 'RFLD_EXPB',
 'RFLD_EXPP',
 'RFLD_EXPPE',
 'RFLD_EXPA',
 'RFLD_EXPT',
 'RFLD_HLRB',
 'RFLD_HLRP',
 'RFLD_HLRA',
 'RFLD_HLRR',
 'RFLD_EALB',
 'RFLD_EALP',
 'RFLD_EALPE',
 'RFLD_EALA',
 'RFLD_EALT',
 'RFLD_EALS',
 'RFLD_EALR',
 'RFLD_ALRB',
 'RFLD_ALRP',
 'RFLD_ALRA',
 'RFLD_ALR_NPCTL',
 'RFLD_RISKV',
 'RFLD_RISKS',
 'RFLD_RISKR',
 'SWND_EVNTS',
 'SWND_AFREQ',
 'SWND_EXP_AREA',
 'SWND_EXPB',
 'SWND_EXPP',
 'SWND_EXPPE',
 'SWND_EXPA',
 'SWND_EXPT',
 'SWND_HLRB',
 'SWND_HLRP',
 'SWND_HLRA',
 'SWND_HLRR',
 'SWND_EALB',
 'SWND_EALP',
 'SWND_EALPE',
 'SWND_EALA',
 'SWND_EALT',
 'SWND_EALS',
 'SWND_EALR',
 'SWND_ALRB',
 'SWND_ALRP',
 'SWND_ALRA',
 'SWND_ALR_NPCTL',
 'SWND_RISKV',
 'SWND_RISKS',
 'SWND_RISKR',
 'TRND_EVNTS',
 'TRND_AFREQ',
 'TRND_EXP_AREA',
 'TRND_EXPB',
 'TRND_EXPP',
 'TRND_EXPPE',
 'TRND_EXPA',
 'TRND_EXPT',
 'TRND_HLRB',
 'TRND_HLRP',
 'TRND_HLRA',
 'TRND_HLRR',
 'TRND_EALB',
 'TRND_EALP',
 'TRND_EALPE',
 'TRND_EALA',
 'TRND_EALT',
 'TRND_EALS',
 'TRND_EALR',
 'TRND_ALRB',
 'TRND_ALRP',
 'TRND_ALRA',
 'TRND_ALR_NPCTL',
 'TRND_RISKV',
 'TRND_RISKS',
 'TRND_RISKR',
 'TSUN_EVNTS',
 'TSUN_AFREQ',
 'TSUN_EXP_AREA',
 'TSUN_EXPB',
 'TSUN_EXPP',
 'TSUN_EXPPE',
 'TSUN_EXPT',
 'TSUN_HLRB',
 'TSUN_HLRP',
 'TSUN_HLRR',
 'TSUN_EALB',
 'TSUN_EALP',
 'TSUN_EALPE',
 'TSUN_EALT',
 'TSUN_EALS',
 'TSUN_EALR',
 'TSUN_ALRB',
 'TSUN_ALRP',
 'TSUN_ALR_NPCTL',
 'TSUN_RISKV',
 'TSUN_RISKS',
 'TSUN_RISKR',
 'VLCN_EVNTS',
 'VLCN_AFREQ',
 'VLCN_EXP_AREA',
 'VLCN_EXPB',
 'VLCN_EXPP',
 'VLCN_EXPPE',
 'VLCN_EXPT',
 'VLCN_HLRB',
 'VLCN_HLRP',
 'VLCN_HLRR',
 'VLCN_EALB',
 'VLCN_EALP',
 'VLCN_EALPE',
 'VLCN_EALT',
 'VLCN_EALS',
 'VLCN_EALR',
 'VLCN_ALRB',
 'VLCN_ALRP',
 'VLCN_ALR_NPCTL',
 'VLCN_RISKV',
 'VLCN_RISKS',
 'VLCN_RISKR',
 'WFIR_EVNTS',
 'WFIR_AFREQ',
 'WFIR_EXP_AREA',
 'WFIR_EXPB',
 'WFIR_EXPP',
 'WFIR_EXPPE',
 'WFIR_EXPA',
 'WFIR_EXPT',
 'WFIR_HLRB',
 'WFIR_HLRP',
 'WFIR_HLRA',
 'WFIR_HLRR',
 'WFIR_EALB',
 'WFIR_EALP',
 'WFIR_EALPE',
 'WFIR_EALA',
 'WFIR_EALT',
 'WFIR_EALS',
 'WFIR_EALR',
 'WFIR_ALRB',
 'WFIR_ALRP',
 'WFIR_ALRA',
 'WFIR_ALR_NPCTL',
 'WFIR_RISKV',
 'WFIR_RISKS',
 'WFIR_RISKR',
 'WNTW_EVNTS',
 'WNTW_AFREQ',
 'WNTW_EXP_AREA',
 'WNTW_EXPB',
 'WNTW_EXPP',
 'WNTW_EXPPE',
 'WNTW_EXPA',
 'WNTW_EXPT',
 'WNTW_HLRB',
 'WNTW_HLRP',
 'WNTW_HLRA',
 'WNTW_HLRR',
 'WNTW_EALB',
 'WNTW_EALP',
 'WNTW_EALPE',
 'WNTW_EALA',
 'WNTW_EALT',
 'WNTW_EALS',
 'WNTW_EALR',
 'WNTW_ALRB',
 'WNTW_ALRP',
 'WNTW_ALRA',
 'WNTW_ALR_NPCTL',
 'WNTW_RISKV',
 'WNTW_RISKS',
 'WNTW_RISKR',
 'NRI_VER']

In [40]:
# Keep only useful columns
climate_va = climate_va[['COUNTY', 'STATE', 'COUNTYFIPS', 'POPULATION',
                         'RISK_SCORE', 'RISK_RATNG', 'EAL_SCORE', 'EAL_RATNG']]

climate_va.head()

,COUNTY,STATE,COUNTYFIPS,POPULATION,RISK_SCORE,RISK_RATNG,EAL_SCORE,EAL_RATNG
0,Accomack,Virginia,1,33367,89.564111,Relatively Moderate,88.888889,Relatively Moderate
1,Albemarle,Virginia,3,112239,64.397073,Relatively Low,67.595172,Relatively Low
2,Alleghany,Virginia,5,15205,14.158447,Very Low,15.134633,Very Low
3,Amelia,Virginia,7,13265,9.417754,Very Low,8.263695,Very Low
4,Amherst,Virginia,9,31300,10.372256,Very Low,10.863510,Very Low

In [41]:
climate_va.shape

(133, 8)

In [42]:
climate_va.duplicated().sum()

0

In [43]:
climate_va.isnull().sum()

COUNTY        0
STATE         0
COUNTYFIPS    0
POPULATION    0
RISK_SCORE    0
RISK_RATNG    0
EAL_SCORE     0
EAL_RATNG     0
dtype: int64

City-to-County Dataset
This file helps me find out what county each city is in.
I need it because my bank data only has city names, and my climate data uses counties.
This dataset lets me connect the two.

In [44]:
city_county = pd.read_csv("City-to-County Dataset.csv")

city_county.head()

          city  state_name  county_name
0     New York    New York       Queens
1  Los Angeles  California  Los Angeles
2      Chicago    Illinois         Cook
3        Miami     Florida   Miami-Dade
4      Houston       Texas       Harris

In [45]:
city_county.columns

Index(['city', 'state_name', 'county_name'], dtype='object')

In [46]:
# Keep only needed columns and filter for Virginia
city_county = city_county[['city', 'county_name', 'state_name']]
city_county = city_county[city_county['state_name'] == 'Virginia']

# Clean city names in both datasets
df['CITY'] = df['CITY'].str.strip().str.upper()
city_county['city'] = city_county['city'].str.strip().str.upper()

In [47]:
# Merge Virginia bank data with city-to-county dataset
df = df.merge(city_county,
              left_on=['CITY', 'STNAME'],
              right_on=['city', 'state_name'],
              how='left')

# Drop extra columns from merge
df = df.drop(columns=['city', 'state_name'])

In [48]:
df.isna().sum()

CERT                       0
NAMEFULL                   0
ADDRESBR                   0
CITY                       0
STNAME                     0
ZIP                        0
DEPSUMBR                   0
NAMEBR                     0
SIMS_ESTABLISHED_DATE      0
SIMS_LATITUDE              0
SIMS_LONGITUDE             0
county_name              158
dtype: int64

In [49]:
df[df['county_name'].isna()]['CITY'].unique()

array(['MC KENNEY', 'BLUE GRASS', 'CARSON', 'RICHMOND CITY'], dtype=object)

In [50]:
# Manual fixes for unmatched cities
df.loc[df['CITY'] == 'MC KENNEY', 'county_name'] = 'DINWIDDIE'
df.loc[df['CITY'] == 'BLUE GRASS', 'county_name'] = 'HIGHLAND'
df.loc[df['CITY'] == 'CARSON', 'county_name'] = 'DINWIDDIE'
df.loc[df['CITY'] == 'RICHMOND CITY', 'county_name'] = 'RICHMOND CITY'

In [51]:
# Make names match before merge
df['county_norm'] = df['county_name'].str.upper().str.replace(' COUNTY','').str.replace(' CITY','').str.strip()
climate_va['COUNTY_NORM'] = climate_va['COUNTY'].str.upper().str.replace(' COUNTY','').str.replace(' CITY','').str.strip()

In [52]:
df.isna().sum()

CERT                     0
NAMEFULL                 0
ADDRESBR                 0
CITY                     0
STNAME                   0
ZIP                      0
DEPSUMBR                 0
NAMEBR                   0
SIMS_ESTABLISHED_DATE    0
SIMS_LATITUDE            0
SIMS_LONGITUDE           0
county_name              0
county_norm              0
dtype: int64

In [53]:
df.duplicated().sum()

0

In [54]:
df['STNAME'].value_counts()

STNAME
Virginia    1436
Name: count, dtype: int64

In [55]:
# Merge Virginia bank data with Virginia climate data
df_va = df.merge(climate_va, left_on='county_norm', right_on='COUNTY_NORM', how='left')

In [56]:
df_va.isnull().sum()

CERT                     0
NAMEFULL                 0
ADDRESBR                 0
CITY                     0
STNAME                   0
ZIP                      0
DEPSUMBR                 0
NAMEBR                   0
SIMS_ESTABLISHED_DATE    0
SIMS_LATITUDE            0
SIMS_LONGITUDE           0
county_name              0
county_norm              0
COUNTY                   0
STATE                    0
COUNTYFIPS               0
POPULATION               0
RISK_SCORE               0
RISK_RATNG               0
EAL_SCORE                0
EAL_RATNG                0
COUNTY_NORM              0
dtype: int64

In [57]:
df_va.duplicated().sum()

0

In [58]:
df_va.columns

Index(['CERT', 'NAMEFULL', 'ADDRESBR', 'CITY', 'STNAME', 'ZIP', 'DEPSUMBR',
       'NAMEBR', 'SIMS_ESTABLISHED_DATE', 'SIMS_LATITUDE', 'SIMS_LONGITUDE',
       'county_name', 'county_norm', 'COUNTY', 'STATE', 'COUNTYFIPS',
       'POPULATION', 'RISK_SCORE', 'RISK_RATNG', 'EAL_SCORE', 'EAL_RATNG',
       'COUNTY_NORM'],
      dtype='object')

In [59]:
df_va = df_va.drop(columns=['county_norm', 'COUNTY_NORM'])

In [60]:
df_va.head()

,CERT,NAMEFULL,ADDRESBR,CITY,STNAME,ZIP,DEPSUMBR,NAMEBR,SIMS_ESTABLISHED_DATE,SIMS_LATITUDE,SIMS_LONGITUDE,county_name,COUNTY,STATE,COUNTYFIPS,POPULATION,RISK_SCORE,RISK_RATNG,EAL_SCORE,EAL_RATNG
0,823,Citizens Bank and Trust Company,126 S Main St,BLACKSTONE,Virginia,23824,151685,Citizens Bank And Trust Company,1873-07-15,37.079760,-77.998135,Nottoway,Nottoway,Virginia,135,15638,21.030862,Very Low,16.805942,Very Low
1,823,Citizens Bank and Trust Company,101 N Main St,BLACKSTONE,Virginia,23824,0,Drive-In Branch,1966-07-29,37.080598,-77.997579,Nottoway,Nottoway,Virginia,135,15638,21.030862,Very Low,16.805942,Very Low
2,823,Citizens Bank and Trust Company,622 E Atlantic St,BLACKSTONE,Virginia,23824,16346,South Hill Branch,2006-11-30,36.721200,-78.119366,Nottoway,Nottoway,Virginia,135,15638,21.030862,Very Low,16.805942,Very Low
3,823,Citizens Bank and Trust Company,2501 Anderson Hwy,BLACKSTONE,Virginia,23824,17559,Powhatan Branch,2019-09-23,37.521730,-77.821405,Nottoway,Nottoway,Virginia,135,15638,21.030862,Very Low,16.805942,Very Low
4,823,Citizens Bank and Trust Company,210 Carter St,BLACKSTONE,Virginia,23824,44082,Crewe Branch,1972-05-31,37.176266,-78.123508,Nottoway,Nottoway,Virginia,135,15638,21.030862,Very Low,16.805942,Very Low

In [61]:
# Rename columns for Virginia
df_va = df_va.rename(columns={
    'CERT': 'cert',
    'NAMEFULL': 'bank_name',
    'ADDRESBR': 'address',
    'CITY': 'city',
    'STNAME': 'state',
    'ZIP': 'zip',
    'DEPSUMBR': 'deposit',
    'NAMEBR': 'branch_name',
    'SIMS_ESTABLISHED_DATE': 'established_date',
    'SIMS_LATITUDE': 'latitude',
    'SIMS_LONGITUDE': 'longitude',
    'county_name': 'county',
    'RISK_SCORE': 'risk_score',
    'RISK_RATNG': 'risk_rating'
})

# Keep only needed columns
df_va = df_va[[
    'cert', 'bank_name', 'address', 'city', 'state', 'zip', 'deposit',
    'branch_name', 'established_date', 'latitude', 'longitude',
    'county', 'risk_score', 'risk_rating'
]]

In [62]:
df_va.columns

Index(['cert', 'bank_name', 'address', 'city', 'state', 'zip', 'deposit',
       'branch_name', 'established_date', 'latitude', 'longitude', 'county',
       'risk_score', 'risk_rating'],
      dtype='object')

In [63]:
df_va.head()

,cert,bank_name,address,city,state,zip,deposit,branch_name,established_date,latitude,longitude,county,risk_score,risk_rating
0,823,Citizens Bank and Trust Company,126 S Main St,BLACKSTONE,Virginia,23824,151685,Citizens Bank And Trust Company,1873-07-15,37.079760,-77.998135,Nottoway,21.030862,Very Low
1,823,Citizens Bank and Trust Company,101 N Main St,BLACKSTONE,Virginia,23824,0,Drive-In Branch,1966-07-29,37.080598,-77.997579,Nottoway,21.030862,Very Low
2,823,Citizens Bank and Trust Company,622 E Atlantic St,BLACKSTONE,Virginia,23824,16346,South Hill Branch,2006-11-30,36.721200,-78.119366,Nottoway,21.030862,Very Low
3,823,Citizens Bank and Trust Company,2501 Anderson Hwy,BLACKSTONE,Virginia,23824,17559,Powhatan Branch,2019-09-23,37.521730,-77.821405,Nottoway,21.030862,Very Low
4,823,Citizens Bank and Trust Company,210 Carter St,BLACKSTONE,Virginia,23824,44082,Crewe Branch,1972-05-31,37.176266,-78.123508,Nottoway,21.030862,Very Low

In [65]:
df_va = df_va.sort_values('risk_score', ascending=False)
df_va = df_va.drop_duplicates(subset=['cert', 'address'], keep='first')

In [66]:
df_va.to_csv("va_clean.csv", index=False)